name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: docker login docker.pkg.github.com --username btwonion --password "$GITHUB_TOKEN"
      - name: Build and Tag
        run: docker build -t docker.pkg.github.com/SickMC/SickBot/SickBot:latest -t docker.pkg.github.com/SickMC/SickBot/SickBot:"$GITHUB_SHA" .
      - name: Push
        run: docker push docker.pkg.github.com/SickMC/SickBot/SickBot:latest
      - name: Push tag
        run: docker push docker.pkg.github.com/SickMC/SickBot/SickBot:"$GITHUB_SHA"
